Assignment/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Assignment.Models
{
    public class Blog
    {
        public int BlogID { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "50 Characters Max")]
        public string Heading { get; set; }
        [Required]
        public string Category { get; set; }
        [Required]
        public string Btags { get; set; }
        [Required]
        public string Content { get; set; }
        public string ImagePath { get; set; }
        public string FileName { get; set; }
        public DateTime CreationDate { get; set; }

       
        /* Careful¬ you might be loading sensitive details that might not be required¬ */
        // public Guid UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        
    }
}

Assignment/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace Assignment.Controllers
{
    public class BlogsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Blogs
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

        // GET: Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blogs/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "BlogID,Heading,Category,Btags,Content,ImagePath,User")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                var user_id = Convert.ToString(blog.User);
                user_id = System.Web.HttpContext.Current.User.Identity.Name.ToString();

                db.Blogs.Add(blog);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blog);
        }

        // GET: Blogs/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlogID,Heading,Category,Btags,Content,ImagePath,FileName,CreationDate")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [HttpPost]
        public ActionResult FileUpload(Blog model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                if (file != null)
                {
                    string pic = System.Guid.NewGuid().ToString() + Path.GetFileName(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/Images/"),pic);
                    file.SaveAs(path);
                    model.ImagePath = "/Images/" + (file.FileName);
                    
                }
                model.CreationDate = DateTime.Now;
                String user_id = System.Web.HttpContext.Current.User.Identity.Name.ToString();
                model.User = db.Users.FirstOrDefault(
                        x => x.UserName == user_id
                    );

                db.Blogs.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return RedirectToAction("Create", model);
        }
    }
}

Assignment/Views/Blogs/Create.cshtml
@model Assignment.Models.Blog

@{
    ViewBag.Title = "Create";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")




    @using (Html.BeginForm("FileUpload", "Blogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Blog</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Heading, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select class="form-control" id="Category" name="Category">
                        <option value="cSharp">C Sharp</option>
                        <option value="CSS">CSS</option>
                        <option value="Java">Java</option>
                        <option value="MVC">MVC</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Btags, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Btags, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Btags, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>


            <div>
                <label for="file">Upload Image:</label>
                <input type="file" name="file" id="file" style="width: 100%;" />
                <br />
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Assignment/Views/Blogs/Delete.cshtml
@model Assignment.Models.Blog

@{
    ViewBag.Title = "Delete";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Blog</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Heading)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Heading)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Category)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Btags)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Btags)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Content)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Content)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ImagePath)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ImagePath)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.FileName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FileName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreationDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreationDate)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Assignment/Views/Blogs/Details.cshtml
@model Assignment.Models.Blog
@{
    ViewBag.Title = "Details";
}

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Details</title>
    </head>
    <body>
        <div class=" container">
            <div class=" row">

                <br />
                <br />
                <br />

                <div class=" col-md-6">
                    @* DISPLAY IMAGE *@
                    @if (!string.IsNullOrEmpty(Model.ImagePath))
        {
            <img src="@Model.ImagePath" style="max-width:200px" />
}
                </div>

                <div class=" col-md-6">

                    <h4>Blog</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Heading)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Heading)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Category)
                        </dt>

                        <dd>
                            @Html.ActionLink(Model.Category, "Index", Model.Category, null, new { style = "color: black" })
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Btags)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Btags)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Content)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Content)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CreationDate)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CreationDate)
                        </dd>



                        <dt>
                            @Html.DisplayNameFor(model => Model.User)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => Model.User.Name)
                        </dd>






                    </dl>

                </div>

            </div>
            </div>

        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.BlogID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </body>
</html>

Assignment/Views/Blogs/Edit.cshtml
@model Assignment.Models.Blog

@{
    ViewBag.Title = "Edit";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Blog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BlogID)

        <div class="form-group">
            @Html.LabelFor(model => model.Heading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" id="Category" name="Category">
                    <option value="cSharp">C Sharp</option>
                    <option value="CSS">CSS</option>
                    <option value="Java">Java</option>
                    <option value="MVC">MVC</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Btags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Btags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Btags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Assignment/Views/Blogs/Index.cshtml
@model IEnumerable<Assignment.Models.Blog>

@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Heading)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Btags)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Heading)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Btags)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.BlogID }) |
                @Html.ActionLink("Details", "Details", new { id=item.BlogID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.BlogID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>